name: tron_tracker
version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
      - ./static:/app/static
    command: >
      bash -c "alembic revision --autogenerate -m 'Initial db' || true && alembic upgrade head && 
               uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - backend

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
      - ./static:/app/static
    depends_on:
      - app
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge